---
- hosts: media_34555
  sudo: yes
  tasks:
  - name: git checkout from remote repo 
    git:
     repo={{ git_repo }}   
     dest={{ site_root_dir }}
     force=yes
#  - name: del nginx-conf
#    file:
#     path={{ site_root_dir }}/nginx-config
#     state=absent
  - name: Gulp 
    shell: 
     free_form=sudo ./gulp
     chdir={{ site_root_dir }}/node_modules/.bin
  handlers:
   - name: nginx restar
     service:
      name=nginx 
      state=restarted
#Created by Punko Punkoivan@yandex.ru on 19.02.16
