---
- hosts: all 
  become: yes
  tasks:
  - name: git checkout from remote repo 
    git:
     repo={{ git_repo }}   
     dest={{ site_root_dir }}
     force=yes
  - name: Gulp 
    shell: 
     free_form=./gulp
     chdir={{ site_root_dir }}/node_modules/.bin
  handlers:
   - name: nginx restar
     service:
      name=nginx 
      state=restarted
#Created by Punko Punkoivan@yandex.ru on 19.02.16
