---
- hosts: media_34555
  sudo: yes
  tasks:
   - name: copy main config into config folder
     template:
      src=nginx.conf.j2
      dest={{ nginx_config_dir }}/nginx.conf
   - name: copy ane4k.in config into site-available folder
     template:
      src=ane4k.in.j2
      dest={{ nginx_config_dir }}/sites-available/ane4k.in
   - name: copy anya.site into site-available folder
     template:
      src=anya.site.j2
      dest={{ nginx_config_dir }}/sites-available/anya.site
   - name: set correct permission for file to use by nginx
     file:
      path={{ site_root_dir }}
      state=directory
      owner={{ nginx_user }}
      group={{ nginx_group }}
      mode=0755
      recurse=yes
   - name: delete nginx-config dir from site_root_folder
      path={{ site_root_dir }}/nginx-config
      state=absent

      
