- hosts: media_34555
  tasks:
   - name: git install
     apt:
      name=git
      state=present
     sudo: yes
   - name: create dir for repo
     file:
       name={{ home }}/site
       state=directory
   - name: Gitclone
     git:
      repo=https://github.com/anechka/portfolio-site.git
      dest={{ home }}/site

